server:
  port: 8090
spring:
  datasource:
    password: osf77
    url: jdbc:postgresql://localhost/circuitbreak?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
resilience4j.circuitbreaker:
  instances:
    avaliacaoCB:
      slidingWindowSize: 8
      minimumNumberOfCalls: 4
