spring:
  datasource:
    password: osf77
    url: jdbc:postgresql://localhost/circuitbreak?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
